##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.18.0-B7] date: [Sat Feb 04 15:50:16 ICT 2023] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = test_modbusrtu_usb

#######################################
# check platform and add DIR
#######################################

ifeq ($(OS),Windows_NT)
	OPENOCD_DIR ?= /d/2_Tool/OpenOCD-20211118-0.11.0
	LIB_DIR ?= /c/Users/Black_Life/STM32Cube/Repository/STM32Cube_FW_F1_V1.8.4
	CC_PATH ?= "/tools/stm32/gcc/bin"
else
	UNAME_S := $(shell uname -s)
	ifeq ($(UNAME_S),Darwin)
		OPENOCD_DIR ?= /usr/local
		LIB_DIR ?= /home/smartth/STM32Cube/Repository/STM32Cube_FW_F1_V1.8.4/
		CC_PATH ?= /Users/nhantt/tools/stm32/gcc-arm-none-eabi-10-2020-q4-major/bin/arm-none-eabi-gcc
	endif
	ifeq ($(UNAME_S),Linux)
		OPENOCD_DIR ?= /usr/local
		LIB_DIR ?= /home/smartth/STM32Cube/Repository/STM32Cube_FW_F1_V1.8.4/
		CC_PATH ?= /Users/nhantt/tools/stm32/gcc-arm-none-eabi-10-2020-q4-major/bin/arm-none-eabi-gcc
	endif
endif

#Check openocd install global
ISOCD_EXIST := $(shell command -v openocd 2> /dev/null)
ifndef ISOCD_EXIST
	OPENOCD    = $(OPENOCD_DIR)/bin/openocd
else
	OPENOCD    = openocd
endif

######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/stm32f1xx_it.c \
Core/Src/stm32f1xx_hal_msp.c \
Core/Src/usb_device.c \
Core/Src/usbd_conf.c \
Core/Src/usbd_desc.c \
Core/Src/usbd_cdc_if.c \
Core/Src/usart.c \
Core/Src/ringbuf.c \
Core/Src/syringe.c \
Core/Src/timeout.c \
Core/Src/tim.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio_ex.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc_ex.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pwr.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash_ex.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_exti.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pcd.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pcd_ex.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_usb.c \
$(LIB_DIR)/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c \
$(LIB_DIR)/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c \
$(LIB_DIR)/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c \
$(LIB_DIR)/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c \
Core/Src/system_stm32f1xx.c \
FreeModbus/functions/mbfunccoils.c \
FreeModbus/functions/mbfuncdiag.c \
FreeModbus/functions/mbfuncdisc.c \
FreeModbus/functions/mbfuncholding.c \
FreeModbus/functions/mbfuncinput.c \
FreeModbus/functions/mbfuncother.c \
FreeModbus/functions/mbutils.c \
FreeModbus/rtu/mbcrc.c \
FreeModbus/rtu/mbrtu.c \
FreeModbus/mb.c \
FreeModbus/app/user_mb_app.c \
FreeModbus/port/portcritical.c \
FreeModbus/port/portevent.c \
FreeModbus/port/portserial.c \
FreeModbus/port/porttimer.c \
FreeModbus/mb_m.c \
FreeModbus/rtu/mbrtu_m.c \
FreeModbus/app/user_mb_app_m.c \
FreeModbus/functions/mbfunccoils_m.c \
FreeModbus/functions/mbfuncdisc_m.c \
FreeModbus/functions/mbfuncholding_m.c \
FreeModbus/functions/mbfuncinput_m.c \
FreeModbus/port/portevent_m.c \
FreeModbus/port/portserial_m.c \
FreeModbus/port/porttimer_m.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_iwdg.c

# ASM sources
ASM_SOURCES =  \
startup_stm32f103xe.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m3

# fpu
# NONE for Cortex-M0/M0+/M3

# float-abi


# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32F103xE


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/STM32F1xx_HAL_Driver/Inc \
-IDrivers/STM32F1xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32F1xx/Include \
-IDrivers/CMSIS/Include \
-I$(LIB_DIR)/Middlewares/ST/STM32_USB_Device_Library/Core/Inc \
-I$(LIB_DIR)/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc \
-IFreeModbus/include \
-IFreeModbus/port \
-IFreeModbus/rtu \
-IFreeModbus/app

# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F103RDTx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys -u _printf_float
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	@$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	@$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# flash
#######################################

# flash:
# 	openocd 	-f interface/stlink-v2.cfg \
# 				-f target/stm32f1x.cfg \
# 		        -c init -c targets -c "reset halt" \
# 		        -c "flash write_image erase $(BUILD_DIR)/$(TARGET).hex" \
# 		        -c "verify_image $(BUILD_DIR)/$(TARGET).hex" \
# 		        -c "reset run" -c shutdown

				
flash:
	$(OPENOCD) 	-f interface/stlink-v2.cfg \
				-f target/stm32f1x.cfg \
		        -c init -c targets -c "reset halt" \
		        -c "flash write_image erase $(BUILD_DIR)/$(TARGET).hex" \
		        -c "verify_image $(BUILD_DIR)/$(TARGET).hex" \
		        -c "reset run" -c shutdown
#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
